version: "3"
services:
  lampachat:
    restart: always
    image: node:18.17.0
    working_dir: /app
    command: npm install || npm run build || npm run start
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    ports:
      - "6002:3000"
