version: "3"
services:
  lampachat:
    image: node:18.17.0
    working_dir: /app
    command: /bin/sh -c "npm install || true; npm run build"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    ports:
      - "6002:3000"
